// Copyright 2018 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kubeflow/pipelines/backend/src/crd/pkg/apis/tensorboard/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTensorboards implements TensorboardInterface
type FakeTensorboards struct {
	Fake *FakeTensorboardV1alpha1
	ns   string
}

var tensorboardsResource = schema.GroupVersionResource{Group: "tensorboard.kubeflow.org", Version: "v1alpha1", Resource: "tensorboards"}

var tensorboardsKind = schema.GroupVersionKind{Group: "tensorboard.kubeflow.org", Version: "v1alpha1", Kind: "Tensorboard"}

// Get takes name of the tensorboard, and returns the corresponding tensorboard object, and an error if there is any.
func (c *FakeTensorboards) Get(name string, options v1.GetOptions) (result *v1alpha1.Tensorboard, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(tensorboardsResource, c.ns, name), &v1alpha1.Tensorboard{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Tensorboard), err
}

// List takes label and field selectors, and returns the list of Tensorboards that match those selectors.
func (c *FakeTensorboards) List(opts v1.ListOptions) (result *v1alpha1.TensorboardList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(tensorboardsResource, tensorboardsKind, c.ns, opts), &v1alpha1.TensorboardList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TensorboardList{ListMeta: obj.(*v1alpha1.TensorboardList).ListMeta}
	for _, item := range obj.(*v1alpha1.TensorboardList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested tensorboards.
func (c *FakeTensorboards) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(tensorboardsResource, c.ns, opts))

}

// Create takes the representation of a tensorboard and creates it.  Returns the server's representation of the tensorboard, and an error, if there is any.
func (c *FakeTensorboards) Create(tensorboard *v1alpha1.Tensorboard) (result *v1alpha1.Tensorboard, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(tensorboardsResource, c.ns, tensorboard), &v1alpha1.Tensorboard{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Tensorboard), err
}

// Update takes the representation of a tensorboard and updates it. Returns the server's representation of the tensorboard, and an error, if there is any.
func (c *FakeTensorboards) Update(tensorboard *v1alpha1.Tensorboard) (result *v1alpha1.Tensorboard, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(tensorboardsResource, c.ns, tensorboard), &v1alpha1.Tensorboard{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Tensorboard), err
}

// Delete takes name of the tensorboard and deletes it. Returns an error if one occurs.
func (c *FakeTensorboards) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(tensorboardsResource, c.ns, name), &v1alpha1.Tensorboard{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTensorboards) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(tensorboardsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.TensorboardList{})
	return err
}

// Patch applies the patch and returns the patched tensorboard.
func (c *FakeTensorboards) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Tensorboard, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(tensorboardsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Tensorboard{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Tensorboard), err
}
