// Copyright 2018 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kubeflow/pipelines/backend/src/crd/pkg/apis/tensorboard/v1alpha1"
	scheme "github.com/kubeflow/pipelines/backend/src/crd/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TensorboardsGetter has a method to return a TensorboardInterface.
// A group's client should implement this interface.
type TensorboardsGetter interface {
	Tensorboards(namespace string) TensorboardInterface
}

// TensorboardInterface has methods to work with Tensorboard resources.
type TensorboardInterface interface {
	Create(*v1alpha1.Tensorboard) (*v1alpha1.Tensorboard, error)
	Update(*v1alpha1.Tensorboard) (*v1alpha1.Tensorboard, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Tensorboard, error)
	List(opts v1.ListOptions) (*v1alpha1.TensorboardList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Tensorboard, err error)
	TensorboardExpansion
}

// tensorboards implements TensorboardInterface
type tensorboards struct {
	client rest.Interface
	ns     string
}

// newTensorboards returns a Tensorboards
func newTensorboards(c *TensorboardV1alpha1Client, namespace string) *tensorboards {
	return &tensorboards{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the tensorboard, and returns the corresponding tensorboard object, and an error if there is any.
func (c *tensorboards) Get(name string, options v1.GetOptions) (result *v1alpha1.Tensorboard, err error) {
	result = &v1alpha1.Tensorboard{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("tensorboards").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Tensorboards that match those selectors.
func (c *tensorboards) List(opts v1.ListOptions) (result *v1alpha1.TensorboardList, err error) {
	result = &v1alpha1.TensorboardList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("tensorboards").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested tensorboards.
func (c *tensorboards) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("tensorboards").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a tensorboard and creates it.  Returns the server's representation of the tensorboard, and an error, if there is any.
func (c *tensorboards) Create(tensorboard *v1alpha1.Tensorboard) (result *v1alpha1.Tensorboard, err error) {
	result = &v1alpha1.Tensorboard{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("tensorboards").
		Body(tensorboard).
		Do().
		Into(result)
	return
}

// Update takes the representation of a tensorboard and updates it. Returns the server's representation of the tensorboard, and an error, if there is any.
func (c *tensorboards) Update(tensorboard *v1alpha1.Tensorboard) (result *v1alpha1.Tensorboard, err error) {
	result = &v1alpha1.Tensorboard{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("tensorboards").
		Name(tensorboard.Name).
		Body(tensorboard).
		Do().
		Into(result)
	return
}

// Delete takes name of the tensorboard and deletes it. Returns an error if one occurs.
func (c *tensorboards) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("tensorboards").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *tensorboards) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("tensorboards").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched tensorboard.
func (c *tensorboards) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Tensorboard, err error) {
	result = &v1alpha1.Tensorboard{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("tensorboards").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
